development:
  adapter: postgresql
  encoding: unicode
  database: XD6-Rails_development
  pool: 5
test:
  adapter: postgresql
  encoding: unicode
  database: XD6-Rails_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: XD6-Rails_production
  pool: 5